//let firstname='hello';
//let firstname='world';
//console.log(firstname);
//output: SyntaxError: Identifier 'firstname' has already been declared

//let firstname='hello';
//firstname='world';
//console.log(firstname);
//output:world 


//CONST--> Constant Variable
 
//const second='tooo';
//console.log(second);

//const second= 'hiii';
//second='helllooo';
//console.log(second);
//output: type error: Assignment to constant variable

const second='hiii';
  const second='helllooo';
console.log(second);
 //output: SyntaxError: Identifier 'second' has already been declared
